Retro/urls.py
from django.urls import path, include
from retro_app.views import Logout
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

urlpatterns = [
    path('retro/',include('retro_app.urls')),
    path('api-auth/',include('rest_framework.urls')),
    path('api-token-auth/',obtain_jwt_token),
    path('api-token-refresh/',refresh_jwt_token),
    path('api-token-verify/',verify_jwt_token),
    path('api-token-kill/',Logout.as_view()),
]

from rest_framework_swagger.views import get_swagger_view
schema_view = get_swagger_view(title='Retro 360 API')
urlpatterns += [
    path('', schema_view)
]

retro/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import AddRetroUserView,RetroUserDeleteView,RetroUserDetailView,RetroUserListView,RetroUserUpdateView

app_name = 'retro'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('signup/',views.user_signup,name='signup'),
    path('login/',views.user_login,name='login'),
    path('create/',views.AddRetroUserView.as_view(),name='create'),
    path('list/',views.RetroUserListView.as_view(),name='list'),
    path('details/<int:pk>',views.RetroUserDetailView.as_view(),name='details'),
    path('delete/<int:pk>',views.RetroUserDeleteView.as_view(),name='delete'),
    path('update/<int:pk>',views.RetroUserUpdateView.as_view(),name='update'),
]
my_patterns = [
    path('create/',AddRetroUserView.as_view(),name='create'),
    path('list/',views.RetroUserListView.as_view(),name='list'),
    path('details/<int:pk>',views.RetroUserDetailView.as_view(),name='details'),
    path('delete/<int:pk>',views.RetroUserDeleteView.as_view(),name='delete'),
    path('update/<int:pk>',views.RetroUserUpdateView.as_view(),name='update'),
]

retro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect

# class RetroUser(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE,default='0')
#     user_type = models.CharField(max_length= 5,default='user')

#     def __str__(self):
#         return "{} {}".format(self.user.username)
    
#     def get_absolute_url(self):
#         return HttpResponseRedirect(reverse('retro:list'))

retro/forms.py
from django import forms
from django.contrib.auth.models import User
from retro.models import RetroUser


class RetroUserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = RetroUser
        fields = '__all__'

class UserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = '__all__'

retro/views.py
from django.shortcuts import render
from django.views.generic import (
            FormView,
            TemplateView,
            ListView,
            DetailView,
            CreateView,
            UpdateView,
            DeleteView)
from .forms import UserForm, RetroUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . import models
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse


from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer
from rest_framework.decorators import api_view, renderer_classes
from rest_framework import response, schemas
from .urls import my_patterns

@api_view()
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='API Docs', patterns=my_patterns, url='/api/v1/')
    return response.Response(generator.get_schema())


class IndexView(TemplateView):
    template_name = 'retro/index.html'

# class AddRetroUserView(FormView):
#     form_class = RetroUserForm
#     template_name = 'retro/create_user_form.html'
#     success_url = 'retro:index'
#     def get_context_data(self,**kwargs):
#         context = super().get_context_data(**kwargs)
#         context['form'] = RetroUserForm
#         return context

#     def form_valid(self,form):
#         form.save()
#         return super().form_valid(form)


class AddRetroUserView(CreateView):
    model = models.RetroUser
    fields = '__all__'
    success_url = reverse_lazy('retro:list')

class RetroUserListView(ListView):
    template_name = 'retro/retrousers_list.html'
    context_object_name = 'retrousers'
    model = models.RetroUser

class RetroUserDetailView(DetailView):
    template_name = 'retro/retrouser_detail.html'
    context_object_name = 'retrouser'
    model = models.RetroUser

class RetroUserDeleteView(DeleteView):
    model = models.RetroUser
    success_url = reverse_lazy('retro:list')

class RetroUserUpdateView(UpdateView):
    model = models.RetroUser
    fields = ['first_name','last_name','email',]
    success_url = reverse_lazy('retro:list')
# CVB form for sign up
"""
class SignUpView(FormView):
    form_class = UserForm
    template_name = 'retro/signup.html'

    form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return redirect('home')
"""
def user_login(request):
    return HttpResponse("TODO")


def user_signup(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request,'retro/signup_form.html',{
        'registered':registered,
        'user_form':user_form,
    })
# Create your views here.

retro/templates/retro/create_user_form.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="container">
        <h2>Test String :{{ test }}</h2>
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="SignUp">
        </form>
    </div> 
{% endblock %}

retro/templates/retro/index.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h2 class="center">Welcome to Reto-360</h2>
        <h3><a href="{% url 'retro:list' %}">Click here to Test CRUD operations</a></h3>
    </div>
{% endblock %}

retro/templates/retro/retro_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <title></title>
    </head>
    <body>

    <!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav> -->
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'retro:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
            </ul>
            <ul class=" navbar-nav ">
              <li class="nav-item navbar-toggler-right">
                  <a class="nav-link" href="{% url 'retro:signup' %}">SignUp</a>
              </li>
              <li class="nav-item navbar-toggler-right">
                  <a class="nav-link" href="{% url 'retro:login' %}">Login</a>
              </li>
            </ul>
        </nav>          
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

retro/templates/retro/retrouser_confirm_delete.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h3>delete {{ retrouser }}?</h3>
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
    </div>
{% endblock %}

retro/templates/retro/retrouser_detail.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h2>Retro User details:</h2>
        <ul>   
            <li>Full Name:{{retrouser.first_name}} {{retrouser.last_name}}</li>
            <li>Mobile :{{ retrouser.mobile}}</li>
            <li>Email : {{ retrouser.email}}</li>
        </ul>
        <a href="{% url 'retro:update' pk=retrouser.pk %}" class="btn btn-warning">Update</a>
        <a href="{% url 'retro:delete' pk=retrouser.pk %}" class="btn btn-danger">Deleted</a>
    </div>
{% endblock %}

retro/templates/retro/retrouser_form.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="jumbotron center">
        <h2>
            {% if not form.instance.pk %}
                Create Retro user
            {% else %}
                Update Retro User
            {% endif %}
        </h2>

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
{% endblock %}

retro/templates/retro/retrousers_list.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h2>Users List</h2>
        <ol>
            {% for user in retrousers %}
            <h3><li><a href="{% url 'retro:details' pk=user.pk %}">{{user.first_name}}</a></li></h3>
            {% endfor %}
        </ol>
        <a href="{% url 'retro:create' %}" class="btn btn-info">Add</a>
    </div>
{% endblock %}

retro/templates/retro/signup_form.html
{% extends 'retro/retro_base.html' %}
{% block body_block %}
    <div class="container">
        {% if not registered %}
        <form method="post">
            {{user_form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="SignUp">
        </form>
        {% else %}
        <div class="jumbotron center">
            <h3>Welcome to Retro-360</h3>
        </div>
        {% endif %}
    </div> 
{% endblock %}